/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import BaseDados.AcessoDespesa;
import BaseDados.ConexaoBD;
import BaseDados.ControleDespesa;
import BaseDados.TabelaDespesa;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Jonathan Andrietti
 */
public class Despesas extends javax.swing.JFrame {

    AcessoDespesa mod = new AcessoDespesa();
    ControleDespesa control = new ControleDespesa();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    
    public Despesas() {
        initComponents();
        preencherTabela("select *from despesas order by tipod");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Conta = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        Dpago = new javax.swing.JLabel();
        Dpagar = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        DpagarD = new javax.swing.JFormattedTextField();
        ValorD = new javax.swing.JFormattedTextField();
        DpagoD = new javax.swing.JFormattedTextField();
        ContaD = new javax.swing.JTextField();
        TipoD = new javax.swing.JTextField();
        Excluir = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Total = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabDesp = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        pesquisa = new javax.swing.JLabel();
        Busca = new javax.swing.JTextField();
        Buscar1 = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 60, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Cadastrar despesas - Editar despesas - Remover despesas - Listar despesas\nFiltro por período (dataInicial – dataFinal) - Filtro por tipo de despesa\nListar total de despesas\n\nAs despesas devem conter as seguintes informações:\nvalor - dataPagamento - dataPagamentoEsperado - tipoDespesa (alimentação, educação, lazer, moradia, roupa, \nsaúde, transporte, outros) - conta\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 890, 150));

        Conta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Conta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Conta.setText("Conta:");
        getContentPane().add(Conta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 30));

        Valor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Valor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Valor.setText("Valor:");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, 30));

        Dpago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dpago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Dpago.setText("Data Pago:");
        getContentPane().add(Dpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 80, 30));

        Dpagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dpagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Dpagar.setText("Data Pagar:");
        getContentPane().add(Dpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 90, 30));

        Tipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Tipo.setText("Tipo Despesa:");
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        DpagarD.setText("01/01/2022");
        DpagarD.setEnabled(false);
        DpagarD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(DpagarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 90, 30));

        ValorD.setText("0,00");
        ValorD.setEnabled(false);
        ValorD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(ValorD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 170, 30));

        DpagoD.setText("01/01/2022");
        DpagoD.setEnabled(false);
        DpagoD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(DpagoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 90, 30));

        ContaD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ContaD.setEnabled(false);
        getContentPane().add(ContaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 560, 30));

        TipoD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TipoD.setEnabled(false);
        getContentPane().add(TipoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 520, 30));

        Excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.setEnabled(false);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 110, 30));

        Salvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salvar.setText("Salvar");
        Salvar.setEnabled(false);
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, 30));

        Editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Editar.setText("Editar");
        Editar.setEnabled(false);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 110, 30));

        Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Total.setText("Total");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 110, 30));

        Novo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        getContentPane().add(Novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 30));

        Listar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        getContentPane().add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 110, 30));

        TabDesp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabDesp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabDespMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabDesp);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 920, 220));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nº Seguência:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 130, 30));

        Codigo.setEditable(false);
        Codigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Codigo.setEnabled(false);
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 160, 30));

        pesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pesquisa.setText("Nome para Busca:");
        getContentPane().add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        Busca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 550, 30));

        Buscar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Buscar1.setText("Buscar");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 110, 30));

        Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setEnabled(false);
        Cancelar.setOpaque(false);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 100, 30));

        setSize(new java.awt.Dimension(937, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Devemos Apagar isso do Mapa???\n\n Só você que tem este Poder");
            if (resposta == JOptionPane.YES_OPTION){
               mod.setCodigo(Integer.parseInt(Codigo.getText()));
               control.Excluir(mod);
            }
        Codigo.setText("");
        TipoD.setText("");
        ContaD.setText("");
        ValorD.setText("");
        DpagoD.setText("");
        DpagarD.setText("");
        Busca.setText("");
        
        Salvar.setEnabled(false);
        Editar.setEnabled(false);
        Excluir.setEnabled(false);
        ValorD.setEnabled(false);
        DpagoD.setEnabled(false);
        DpagarD.setEnabled(false);
        TipoD.setEnabled(false);
        ContaD.setEnabled(false);
        Cancelar.setEnabled(false);    
            
    }//GEN-LAST:event_ExcluirActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        flag=1;
        Salvar.setEnabled(true);
        Editar.setEnabled(true);
        Excluir.setEnabled(true);
        ValorD.setEnabled(true);
        DpagoD.setEnabled(true);
        DpagarD.setEnabled(true);
        TipoD.setEnabled(true);
        ContaD.setEnabled(true);
        Cancelar.setEnabled(true);
    }//GEN-LAST:event_NovoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if (flag==1){
        mod.setTipoD(TipoD.getText());
        mod.setContaD(ContaD.getText());
        mod.setValorD(Integer.parseInt (ValorD.getText()));
        mod.setDpagoD(Integer.parseInt (DpagoD.getText()));
        mod.setDpagarD(Integer.parseInt (DpagarD.getText()));
        control.Salvar(mod);
        TipoD.setText("");
        ContaD.setText("");
        ValorD.setText("");
        DpagoD.setText("");
        DpagarD.setText("");
        
        Salvar.setEnabled(false);
        Editar.setEnabled(false);
        Excluir.setEnabled(false);
        ValorD.setEnabled(false);
        DpagoD.setEnabled(false);
        DpagarD.setEnabled(false);
        TipoD.setEnabled(false);
        ContaD.setEnabled(false);
        Cancelar.setEnabled(false);
        }else{
        mod.setCodigo((Integer.parseInt(Codigo.getText())));
        mod.setTipoD(TipoD.getText());
        mod.setContaD(ContaD.getText());
        mod.setValorD(Integer.parseInt (ValorD.getText()));
        mod.setDpagoD(Integer.parseInt (DpagoD.getText()));
        mod.setDpagarD(Integer.parseInt (DpagarD.getText()));
        control.Editar(mod);
        TipoD.setText("");
        ContaD.setText("");
        ValorD.setText("");
        DpagoD.setText("");
        DpagarD.setText("");
        
        Salvar.setEnabled(false);
        Editar.setEnabled(false);
        Excluir.setEnabled(false);
        ValorD.setEnabled(false);
        DpagoD.setEnabled(false);
        DpagarD.setEnabled(false);
        TipoD.setEnabled(false);
        ContaD.setEnabled(false);
        Cancelar.setEnabled(false);
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
        mod.setBusca(Busca.getText());
        AcessoDespesa model = control.buscarDespesa(mod);
        Codigo.setText(String.valueOf(model.getCodigo()));
        ValorD.setText(String.valueOf(model.getValorD()));
        DpagoD.setText(String.valueOf(model.getDpagoD()));
        DpagarD.setText(String.valueOf(model.getDpagarD()));
        TipoD.setText(model.getTipoD());
        ContaD.setText(model.getContaD());
        Editar.setEnabled(true);
        Excluir.setEnabled(true);
        Cancelar.setEnabled(true);
    }//GEN-LAST:event_Buscar1ActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        flag = 2;
        Salvar.setEnabled(true);
        Editar.setEnabled(true);
        Excluir.setEnabled(true);
        ValorD.setEnabled(true);
        DpagoD.setEnabled(true);
        DpagarD.setEnabled(true);
        TipoD.setEnabled(true);
        ContaD.setEnabled(true);
        Cancelar.setEnabled(true);
    }//GEN-LAST:event_EditarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        TipoD.setText("");
        ContaD.setText("");
        ValorD.setText("");
        DpagoD.setText("");
        DpagarD.setText("");

        Salvar.setEnabled(false);
        Editar.setEnabled(false);
        Excluir.setEnabled(false);
        ValorD.setEnabled(false);
        DpagoD.setEnabled(false);
        DpagarD.setEnabled(false);
        TipoD.setEnabled(false);
        ContaD.setEnabled(false);
        Cancelar.setEnabled(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void TabDespMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabDespMouseClicked
        String tipod =""+TabDesp.getValueAt(TabDesp.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("select *from despesas where tipod='"+tipod+"'");
        try {
            conex.rs.first();
            Codigo.setText(String.valueOf(conex.rs.getInt("codigo")));
            ValorD.setText(String.valueOf(conex.rs.getInt("valord")));
            DpagoD.setText(String.valueOf(conex.rs.getInt("dpagod")));
            DpagarD.setText(String.valueOf(conex.rs.getInt("dpagard")));
            TipoD.setText(conex.rs.getString("tipod"));
            ContaD.setText(conex.rs.getString("contad"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados"+ex);
        }
        
        
        conex.desconecta();
        Editar.setEnabled(true);
        Excluir.setEnabled(true);
    }//GEN-LAST:event_TabDespMouseClicked

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Codigo","ValorD","DpagoD","DpagarD","TipoD","ContaD"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("codigo"),conex.rs.getInt("valord"),conex.rs.getInt("dpagod"),conex.rs.getInt("dpagard"),conex.rs.getString("tipod"),conex.rs.getString("contad")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher ArrayList"+ex);
        }
        TabelaDespesa modelo = new TabelaDespesa(dados, colunas);
        
        TabDesp.setModel(modelo);
        TabDesp.getColumnModel().getColumn(0).setPreferredWidth(78);
        TabDesp.getColumnModel().getColumn(0).setResizable(false);
        TabDesp.getColumnModel().getColumn(1).setPreferredWidth(100);
        TabDesp.getColumnModel().getColumn(1).setResizable(false);
        TabDesp.getColumnModel().getColumn(2).setPreferredWidth(100);
        TabDesp.getColumnModel().getColumn(2).setResizable(false); 
        TabDesp.getColumnModel().getColumn(3).setPreferredWidth(100);
        TabDesp.getColumnModel().getColumn(3).setResizable(false);            
        TabDesp.getColumnModel().getColumn(4).setPreferredWidth(385);
        TabDesp.getColumnModel().getColumn(4).setResizable(false);
        TabDesp.getColumnModel().getColumn(5).setPreferredWidth(150);
        TabDesp.getColumnModel().getColumn(5).setResizable(false);
        TabDesp.getTableHeader().setReorderingAllowed(false);
        TabDesp.setAutoResizeMode(TabDesp.AUTO_RESIZE_OFF);
        TabDesp.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
        conex.desconecta();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Despesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Despesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Busca;
    private javax.swing.JButton Buscar1;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JLabel Conta;
    private javax.swing.JTextField ContaD;
    private javax.swing.JLabel Dpagar;
    private javax.swing.JFormattedTextField DpagarD;
    private javax.swing.JLabel Dpago;
    private javax.swing.JFormattedTextField DpagoD;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Listar;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Salvar;
    private javax.swing.JTable TabDesp;
    private javax.swing.JLabel Tipo;
    private javax.swing.JTextField TipoD;
    private javax.swing.JButton Total;
    private javax.swing.JLabel Valor;
    private javax.swing.JFormattedTextField ValorD;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel pesquisa;
    // End of variables declaration//GEN-END:variables
}
