/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan Andrietti
 */
public class Entrada extends javax.swing.JFrame {

    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DSenha = new javax.swing.JLabel();
        DNome = new javax.swing.JLabel();
        NomeAcesso = new javax.swing.JTextField();
        SenhaAcesso = new javax.swing.JPasswordField();
        Sair = new javax.swing.JButton();
        Entrar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle suas Finanças - Ganhos e Gastos!");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 771, 41);

        DSenha.setBackground(new java.awt.Color(153, 153, 255));
        DSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DSenha.setText("Senha:");
        DSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        DSenha.setOpaque(true);
        getContentPane().add(DSenha);
        DSenha.setBounds(150, 260, 90, 30);

        DNome.setBackground(new java.awt.Color(153, 153, 255));
        DNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DNome.setText("Nome:");
        DNome.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        DNome.setOpaque(true);
        getContentPane().add(DNome);
        DNome.setBounds(150, 210, 90, 30);

        NomeAcesso.setBackground(new java.awt.Color(204, 255, 255));
        NomeAcesso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NomeAcesso.setText("Admin");
        getContentPane().add(NomeAcesso);
        NomeAcesso.setBounds(250, 210, 310, 30);

        SenhaAcesso.setText("12345");
        getContentPane().add(SenhaAcesso);
        SenhaAcesso.setBounds(250, 260, 310, 30);

        Sair.setBackground(new java.awt.Color(255, 204, 204));
        Sair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sair.setText("Sair");
        Sair.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Sair.setOpaque(false);
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(640, 260, 120, 30);

        Entrar1.setBackground(new java.awt.Color(255, 204, 204));
        Entrar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Entrar1.setText("Entrar");
        Entrar1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Entrar1.setOpaque(false);
        Entrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar1);
        Entrar1.setBounds(640, 210, 120, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Seguro-garantia-judicial.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -10, 950, 430);

        setSize(new java.awt.Dimension(950, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void Entrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar1ActionPerformed
        if (NomeAcesso.getText().equals("Admin")&& SenhaAcesso.getText().equals("12345")){
            SistemaBase tela = new SistemaBase();
            tela.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Problema no Acesso! Use para acessar:\n Nome: Admin\n Senha: 12345");
        }
    }//GEN-LAST:event_Entrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNome;
    private javax.swing.JLabel DSenha;
    private javax.swing.JButton Entrar1;
    private javax.swing.JTextField NomeAcesso;
    private javax.swing.JButton Sair;
    private javax.swing.JPasswordField SenhaAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
