/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import BaseDados.AcessoReceita;
import BaseDados.ConexaoBD;
import BaseDados.ControleReceita;
import BaseDados.TabelaReceita;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Jonathan Andrietti
 */
public class Receitas extends javax.swing.JFrame {

    AcessoReceita mod = new AcessoReceita();
    ControleReceita control = new ControleReceita();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    
            
    public Receitas() {
        initComponents();
        preencherTabela("select *from receitas order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sair = new javax.swing.JButton();
        codigo = new javax.swing.JLabel();
        codigo1 = new javax.swing.JLabel();
        codigo2 = new javax.swing.JLabel();
        codigo3 = new javax.swing.JLabel();
        codigo4 = new javax.swing.JLabel();
        codigo5 = new javax.swing.JLabel();
        codigo6 = new javax.swing.JLabel();
        Treceita = new javax.swing.JTextField();
        Valor = new javax.swing.JTextField();
        Nome = new javax.swing.JTextField();
        Conta = new javax.swing.JTextField();
        Excluir = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Total = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        Codigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabReceita = new javax.swing.JTable();
        Dpago = new javax.swing.JFormattedTextField();
        Dpagar = new javax.swing.JFormattedTextField();
        Salvar = new javax.swing.JButton();
        pesquisa = new javax.swing.JLabel();
        Busca = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Receitas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 60, -1));

        codigo.setBackground(new java.awt.Color(153, 255, 255));
        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo.setText("Tipo de Receita:");
        codigo.setOpaque(true);
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 140, 30));

        codigo1.setBackground(new java.awt.Color(153, 255, 255));
        codigo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo1.setText("Código:");
        codigo1.setOpaque(true);
        getContentPane().add(codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, 30));

        codigo2.setBackground(new java.awt.Color(153, 255, 255));
        codigo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo2.setText("Valor:");
        codigo2.setOpaque(true);
        getContentPane().add(codigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 30));

        codigo3.setBackground(new java.awt.Color(153, 255, 255));
        codigo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo3.setText("Data Recebido:");
        codigo3.setOpaque(true);
        getContentPane().add(codigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, 30));

        codigo4.setBackground(new java.awt.Color(153, 255, 255));
        codigo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo4.setText("Data Pagar:");
        codigo4.setOpaque(true);
        getContentPane().add(codigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 110, 30));

        codigo5.setBackground(new java.awt.Color(153, 255, 255));
        codigo5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo5.setText("Nome / Descrição:");
        codigo5.setOpaque(true);
        getContentPane().add(codigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 140, 30));

        codigo6.setBackground(new java.awt.Color(153, 255, 255));
        codigo6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codigo6.setText("Conta:");
        codigo6.setOpaque(true);
        getContentPane().add(codigo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 80, 30));

        Treceita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Treceita.setEnabled(false);
        getContentPane().add(Treceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 420, 30));

        Valor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Valor.setEnabled(false);
        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 30));

        Nome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nome.setEnabled(false);
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 420, 30));

        Conta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Conta.setEnabled(false);
        getContentPane().add(Conta, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 330, 30));

        Excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.setEnabled(false);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 110, 30));

        Novo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        getContentPane().add(Novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, 30));

        Editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Editar.setText("Editar");
        Editar.setEnabled(false);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, 30));

        Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Total.setText("Total");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 110, 30));

        Buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 110, 30));

        Listar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        getContentPane().add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 110, 30));

        Codigo.setEditable(false);
        Codigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Codigo.setEnabled(false);
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, 30));

        TabReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabReceitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabReceita);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 990, 300));

        Dpago.setEnabled(false);
        Dpago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpagoActionPerformed(evt);
            }
        });
        getContentPane().add(Dpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, 30));

        Dpagar.setEnabled(false);
        Dpagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpagarActionPerformed(evt);
            }
        });
        getContentPane().add(Dpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 100, 30));

        Salvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salvar.setText("Salvar");
        Salvar.setEnabled(false);
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 110, 30));

        pesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pesquisa.setText("Nome para Busca:");
        getContentPane().add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        Busca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 550, 30));

        Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setEnabled(false);
        Cancelar.setOpaque(false);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 110, 30));

        setSize(new java.awt.Dimension(1035, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorActionPerformed

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Devemos Apagar isso do Mapa???\n\n Só você que tem este Poder");
            if (resposta == JOptionPane.YES_OPTION){
               mod.setCodigo(Integer.parseInt(Codigo.getText()));
               control.Excluir(mod);
            }
            Codigo.setText("");
            Nome.setText("");
            Valor.setText("");
            Treceita.setText("");
            Dpago.setText("");
            Dpagar.setText("");
            Conta.setText("");
            Busca.setText("");
            Nome.setEnabled(false);
            Valor.setEnabled(false);
            Treceita.setEnabled(false);
            Dpago.setEnabled(false);
            Dpagar.setEnabled(false);
            Conta.setEnabled(false);
            Salvar.setEnabled(false);
            Editar.setEnabled(false);
            Excluir.setEnabled(false);
    }//GEN-LAST:event_ExcluirActionPerformed

    
    
    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarActionPerformed

    private void DpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DpagoActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        flag=1;
        Salvar.setEnabled(true);
        Editar.setEnabled(false);
        Excluir.setEnabled(true);
        Nome.setEnabled(true);
        Valor.setEnabled(true);
        Treceita.setEnabled(true);
        Dpago.setEnabled(true);
        Dpagar.setEnabled(true);
        Conta.setEnabled(true);
        Cancelar.setEnabled(true);               
    }//GEN-LAST:event_NovoActionPerformed

    private void DpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DpagarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if (flag==1){
        mod.setNome(Nome.getText());
        mod.setValor(Integer.parseInt (Valor.getText()));
        mod.setTreceita(Treceita.getText());
        mod.setConta(Conta.getText());
        mod.setDpago(Integer.parseInt (Dpago.getText()));
        mod.setDpagar(Integer.parseInt (Dpagar.getText()));        
        control.Salvar(mod);
        Nome.setText("");
        Valor.setText("");
        Treceita.setText("");
        Dpago.setText("");
        Dpagar.setText("");
        Conta.setText("");
        Nome.setEnabled(false);
        Valor.setEnabled(false);
        Treceita.setEnabled(false);
        Dpago.setEnabled(false);
        Dpagar.setEnabled(false);
        Conta.setEnabled(false);
        Salvar.setEnabled(false);
        Editar.setEnabled(false);
        Excluir.setEnabled(false);
        }else{
           mod.setCodigo((Integer.parseInt(Codigo.getText())));
           mod.setNome(Nome.getText());
           mod.setValor((Integer.parseInt(Valor.getText())));
           mod.setTreceita(Treceita.getText());
           mod.setDpago((Integer.parseInt(Dpago.getText())));
           mod.setDpagar((Integer.parseInt(Dpagar.getText())));
           mod.setConta(Conta.getText());
           control.Editar(mod);
           Nome.setEnabled(false);
           Valor.setEnabled(false);
           Treceita.setEnabled(false);
           Dpago.setEnabled(false);
           Dpagar.setEnabled(false);
           Conta.setEnabled(false);
           Salvar.setEnabled(false);
           Editar.setEnabled(false);
           Excluir.setEnabled(false);
           Nome.setText("");
           Valor.setText("");
           Treceita.setText("");
           Dpago.setText("");
           Dpagar.setText("");
           Conta.setText("");
           
        }
        
    }//GEN-LAST:event_SalvarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        mod.setBusca(Busca.getText());
        AcessoReceita model = control.buscarReceita(mod);
        Codigo.setText(String.valueOf(model.getCodigo()));
        Nome.setText(model.getNome());
        Valor.setText(String.valueOf(model.getValor()));
        Treceita.setText(model.getTreceita());
        Dpago.setText(String.valueOf(model.getDpago()));
        Dpagar.setText(String.valueOf(model.getDpagar()));
        Conta.setText(model.getConta());
        Editar.setEnabled(true);
        Excluir.setEnabled(true);
    }//GEN-LAST:event_BuscarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        flag = 2;
        Salvar.setEnabled(true);
        Editar.setEnabled(false);
        Excluir.setEnabled(true);
        Nome.setEnabled(true);
        Valor.setEnabled(true);
        Treceita.setEnabled(true);
        Dpago.setEnabled(true);
        Dpagar.setEnabled(true);
        Conta.setEnabled(true);
        Cancelar.setEnabled(true);
    }//GEN-LAST:event_EditarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Nome.setText("");
        Valor.setText("");
        Treceita.setText("");
        Dpago.setText("");
        Dpagar.setText("");
        Conta.setText("");
        Nome.setEnabled(false);
        Valor.setEnabled(false);
        Treceita.setEnabled(false);
        Dpago.setEnabled(false);
        Dpagar.setEnabled(false);
        Conta.setEnabled(false);
        Salvar.setEnabled(false);
        Editar.setEnabled(false);
        Excluir.setEnabled(false);
        Cancelar.setEnabled(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void TabReceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabReceitaMouseClicked
        String nome = ""+TabReceita.getValueAt(TabReceita.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("select *from receitas where nome='"+nome+"'");
        try {
            conex.rs.first();
            Codigo.setText(String.valueOf(conex.rs.getInt("codigo")));
            Nome.setText(conex.rs.getString("nome"));
            Valor.setText(String.valueOf(conex.rs.getInt("valor")));
            Treceita.setText(conex.rs.getString("treceita"));
            Dpago.setText(String.valueOf(conex.rs.getInt("dpago")));
            Dpagar.setText(String.valueOf(conex.rs.getInt("dpagar")));
            Conta.setText(conex.rs.getString("conta"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados"+ex);
        }
        
        
        conex.desconecta();
        Editar.setEnabled(true);
        Excluir.setEnabled(true);
    }//GEN-LAST:event_TabReceitaMouseClicked
    
     public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Codigo","Nome","Valor","Treceita","Dpago","Dpagar","Conta"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("codigo"),conex.rs.getString("nome"),conex.rs.getInt("valor"),conex.rs.getString("treceita"),conex.rs.getInt("dpago"),conex.rs.getInt("dpagar"),conex.rs.getString("conta")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher ArrayList"+ex);
        }
        TabelaReceita modelo = new TabelaReceita(dados, colunas);
        
        TabReceita.setModel(modelo);
        TabReceita.getColumnModel().getColumn(0).setPreferredWidth(60);
        TabReceita.getColumnModel().getColumn(0).setResizable(false);
        TabReceita.getColumnModel().getColumn(1).setPreferredWidth(300);
        TabReceita.getColumnModel().getColumn(1).setResizable(false);
        TabReceita.getColumnModel().getColumn(2).setPreferredWidth(80);
        TabReceita.getColumnModel().getColumn(2).setResizable(false); 
        TabReceita.getColumnModel().getColumn(3).setPreferredWidth(250);
        TabReceita.getColumnModel().getColumn(3).setResizable(false);            
        TabReceita.getColumnModel().getColumn(4).setPreferredWidth(80);
        TabReceita.getColumnModel().getColumn(4).setResizable(false);            
        TabReceita.getColumnModel().getColumn(5).setPreferredWidth(80);
        TabReceita.getColumnModel().getColumn(5).setResizable(false);            
        TabReceita.getColumnModel().getColumn(6).setPreferredWidth(140);
        TabReceita.getColumnModel().getColumn(6).setResizable(false);            
        TabReceita.getTableHeader().setReorderingAllowed(false);
        TabReceita.setAutoResizeMode(TabReceita.AUTO_RESIZE_OFF);
        TabReceita.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
        conex.desconecta();
    }
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Busca;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Conta;
    private javax.swing.JFormattedTextField Dpagar;
    private javax.swing.JFormattedTextField Dpago;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Listar;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Salvar;
    private javax.swing.JTable TabReceita;
    private javax.swing.JButton Total;
    private javax.swing.JTextField Treceita;
    private javax.swing.JTextField Valor;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel codigo1;
    private javax.swing.JLabel codigo2;
    private javax.swing.JLabel codigo3;
    private javax.swing.JLabel codigo4;
    private javax.swing.JLabel codigo5;
    private javax.swing.JLabel codigo6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pesquisa;
    // End of variables declaration//GEN-END:variables
}
