/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import BaseDados.ConexaoBD;

/**
 *
 * @author Jonathan Andrietti
 */
public class SistemaBase extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    
    public SistemaBase() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenuSistema = new javax.swing.JMenuBar();
        ReceitasS = new javax.swing.JMenu();
        ReceitasSistema = new javax.swing.JMenuItem();
        ContaS = new javax.swing.JMenu();
        ContasSistema = new javax.swing.JMenuItem();
        Despesas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        SobreS = new javax.swing.JMenu();
        SobreSistema = new javax.swing.JMenuItem();
        SairS = new javax.swing.JMenu();
        SairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Finaças Pessoais.");
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FinancasMundi.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1470, 800);

        ReceitasS.setText("Receitas");

        ReceitasSistema.setText("Receitas");
        ReceitasSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceitasSistemaActionPerformed(evt);
            }
        });
        ReceitasS.add(ReceitasSistema);

        MenuSistema.add(ReceitasS);

        ContaS.setText("Contas");

        ContasSistema.setText("Contas");
        ContasSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContasSistemaActionPerformed(evt);
            }
        });
        ContaS.add(ContasSistema);

        MenuSistema.add(ContaS);

        Despesas.setText("Despesas");

        jMenuItem1.setText("Despesas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Despesas.add(jMenuItem1);

        MenuSistema.add(Despesas);

        SobreS.setText("Sobre");

        SobreSistema.setText("Sobre o Sistema");
        SobreSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreSistemaActionPerformed(evt);
            }
        });
        SobreS.add(SobreSistema);

        MenuSistema.add(SobreS);

        SairS.setText("Sair");

        SairSistema.setText("Sair do Sistema");
        SairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairSistemaActionPerformed(evt);
            }
        });
        SairS.add(SairSistema);

        MenuSistema.add(SairS);

        setJMenuBar(MenuSistema);

        setSize(new java.awt.Dimension(1245, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairSistemaActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_SairSistemaActionPerformed

    private void SobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreSistemaActionPerformed
        Informacao tela = new Informacao();
        tela.setVisible(true);
    }//GEN-LAST:event_SobreSistemaActionPerformed

    private void ReceitasSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceitasSistemaActionPerformed
        Receitas tela = new Receitas();
        tela.setVisible(true);
    }//GEN-LAST:event_ReceitasSistemaActionPerformed

    private void ContasSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContasSistemaActionPerformed
        Contas tela = new Contas();
        tela.setVisible(true);
    }//GEN-LAST:event_ContasSistemaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Despesas tela = new Despesas();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ContaS;
    private javax.swing.JMenuItem ContasSistema;
    private javax.swing.JMenu Despesas;
    private javax.swing.JMenuBar MenuSistema;
    private javax.swing.JMenu ReceitasS;
    private javax.swing.JMenuItem ReceitasSistema;
    private javax.swing.JMenu SairS;
    private javax.swing.JMenuItem SairSistema;
    private javax.swing.JMenu SobreS;
    private javax.swing.JMenuItem SobreSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
