/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

/**
 *
 * @author Jonathan Andrietti
 */
public class CadReceitas extends javax.swing.JFrame {

    /**
     * Creates new form CadReceitas
     */
    public CadReceitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDataRber = new javax.swing.JFormattedTextField();
        jValor = new javax.swing.JFormattedTextField();
        jDataRdo = new javax.swing.JFormattedTextField();
        jTipoR = new javax.swing.JTextField();
        jConta = new javax.swing.JComboBox();
        jNovo = new javax.swing.JButton();
        jSalvar = new javax.swing.JButton();
        jLimpar = new javax.swing.JButton();
        jEditar = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Valor:");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 28, 131, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Data à Receber:");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 74, 131, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Data Recebido:");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 120, 131, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Conta:");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(12, 166, 131, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo Receita:");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(12, 212, 131, 28);

        jDataRber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel1.add(jDataRber);
        jDataRber.setBounds(153, 74, 297, 28);

        jValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        jValor.setText("0,00");
        jValor.setToolTipText("0,00");
        jPanel1.add(jValor);
        jValor.setBounds(153, 28, 297, 28);

        jDataRdo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel1.add(jDataRdo);
        jDataRdo.setBounds(153, 120, 297, 28);

        jTipoR.setText("Origem do Valor");
        jPanel1.add(jTipoR);
        jTipoR.setBounds(153, 212, 297, 28);

        jConta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jonathan Banco Brasil", "Jonathan Banco Ton", "Jonathan Banco Bradesco", "Jonathan Banco PicPay", "Jonathan Banco Mercado Pago" }));
        jPanel1.add(jConta);
        jConta.setBounds(153, 166, 297, 28);

        jNovo.setBackground(new java.awt.Color(255, 204, 51));
        jNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNovo.setText("Novo");
        jNovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jNovo);
        jNovo.setBounds(500, 30, 102, 39);

        jSalvar.setBackground(new java.awt.Color(255, 204, 51));
        jSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSalvar.setText("Salvar");
        jSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSalvar);
        jSalvar.setBounds(620, 30, 102, 39);

        jLimpar.setBackground(new java.awt.Color(255, 204, 51));
        jLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLimpar.setText("Limpar");
        jLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLimpar);
        jLimpar.setBounds(740, 30, 102, 39);

        jEditar.setBackground(new java.awt.Color(255, 204, 51));
        jEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEditar.setText("Editar");
        jEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jEditar);
        jEditar.setBounds(560, 90, 102, 39);

        jExcluir.setBackground(new java.awt.Color(255, 204, 51));
        jExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jExcluir.setText("Excluir");
        jExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jExcluir);
        jExcluir.setBounds(680, 90, 102, 39);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(12, 257, 846, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 870, 450);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Receitas");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(324, 11, 236, 26);

        setSize(new java.awt.Dimension(906, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadReceitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jConta;
    private javax.swing.JFormattedTextField jDataRber;
    private javax.swing.JFormattedTextField jDataRdo;
    private javax.swing.JButton jEditar;
    private javax.swing.JButton jExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jLimpar;
    private javax.swing.JButton jNovo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTipoR;
    private javax.swing.JFormattedTextField jValor;
    // End of variables declaration//GEN-END:variables
}
